baseURL = "/"
languageCode = "it-it"
DefaultContentLanguage = "it"
title = "Covid19Alessandria.help"
theme = "bootstrap"
enableRobotsTXT = true

[frontmatter]
    lastmod = [":fileModTime", ":default"]

[taxonomies]
    categoria = "categoria"

[params]
    author = "lab121.org"
    description = "Un progetto per condividere informazioni e attivarsi a supporto dell'emergenza COVID19"
    footer = "Made with Love for Alessandria"
    images = ["images/banner/covid19alessandriahelp_banner_quadrato.png"]
    prodURL = "https://covid19alessandria.help"

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = ["title"]
    params = []

[outputFormats.Opendata]
    baseName = "opendata"
    isPlainText = true
    mediaType = "text/csv"
    notAlternative = true

[outputs]
    home = ["HTML", "RSS", "Algolia", "Opendata"]

[sitemap]
    changefreq = "monthly"
